//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Home_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Home_Index() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Home_Index", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 不甘平凡，勇于探索，创新创业充满未知与风险，答案只在前方。 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们的理念 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 坚持创新，必能成就！ 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 美娱力求将各种类型的智能技术应用于互动教育、互动娱乐等领域，提升用户体验和改善学习效果。经历多次变迁，我们核心项目已从“互动演艺平台”、“互动卡通”项目，演变为当前的“英语爸爸”整合互动教育项目。 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_01_Content {
            get {
                return ResourceManager.GetString("Sec_Intro_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 1. 自主品牌项目 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_01_Name {
            get {
                return ResourceManager.GetString("Sec_Intro_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们提供软件产品从创意到实现的全生命周期咨询和服务，协助客户将伟大创意一步步带入现实世界。 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_02_Content {
            get {
                return ResourceManager.GetString("Sec_Intro_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2. 软件技术服务 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_02_Name {
            get {
                return ResourceManager.GetString("Sec_Intro_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 面向未来，我们的研究涵盖电子商务、人工智能、人体感知、空间感知、虚拟互动等领域，并积极寻找各类技术方案的落地可行性。 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_03_Content {
            get {
                return ResourceManager.GetString("Sec_Intro_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 3. 技术研究 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_03_Name {
            get {
                return ResourceManager.GetString("Sec_Intro_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 苏州美娱络科技有限公司是2010年5月成立于苏州的一家创业型企业，由具有多年500强和娱乐技术产业链上游企业工作经验的海归人员所创立。 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_SubTitle {
            get {
                return ResourceManager.GetString("Sec_Intro_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们致力于研究和开发下一代互动技术，探寻相关技术与娱乐、教育应用的融合，并推动新型商业模式在中国的产业化与市场化。 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_SubTitle1 {
            get {
                return ResourceManager.GetString("Sec_Intro_SubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 美娱简介 的本地化字符串。
        /// </summary>
        internal static string Sec_Intro_Title {
            get {
                return ResourceManager.GetString("Sec_Intro_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 一个让孩子们快乐学习英语的整合式平台 的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_SubTitle {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”项目 的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_Title {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady - 苏州美娱 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
