//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Home_About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Home_About() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Home_About", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 “imady”是家喻户晓、朗朗上口的英文&quot;I Made It！&quot;的谐音缩写，代表了在互联网和科技飞速发展、个性文化在世界范围内得到宣扬的时代中，一种敢于创造、敢于冒险的精神理念和自我价值的肯定。“imady”文字及图形已经由苏州美娱网络科技有限公司注册了中国商标并获批准。 的本地化字符串。
        /// </summary>
        internal static string Sec_Brand_AboutBrand_Content {
            get {
                return ResourceManager.GetString("Sec_Brand_AboutBrand_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关于imady品牌 的本地化字符串。
        /// </summary>
        internal static string Sec_Brand_AboutBrand_Name {
            get {
                return ResourceManager.GetString("Sec_Brand_AboutBrand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &quot;imady&quot;来自于英文口语&quot;I made it !&quot;的谐音，表达了追求、抱负和创新的精神。imady的logo包含了一个英文字母“i”和一个感叹号“！”，两个符号紧密结合，绿色代表了一种自我价值的生命力，红色则是“成功的喜悦”，整体含义更加面向新一代互联网用户开放的性格和渴望分享和认同的价值观，是对于虚拟网络世界“自由无边界”精神的一种拥抱。 的本地化字符串。
        /// </summary>
        internal static string Sec_Brand_Connotation_Content {
            get {
                return ResourceManager.GetString("Sec_Brand_Connotation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &quot;imady&quot;的含义 的本地化字符串。
        /// </summary>
        internal static string Sec_Brand_Connotation_Name {
            get {
                return ResourceManager.GetString("Sec_Brand_Connotation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 美娱致力于将最前沿的互动科技应用于各种线上教育、培训、娱乐等类型的应用，并力争形成新的商业模式。基于下一代高速网络、高速移动互联网的基础架构，我们看到未来10年的时间内，人工智能、机器智能、人体感知、空间感知、虚拟人机互动等全新的技术将逐渐渗透到我们的生活，将这些科技创造性地融入当前线上娱乐和互动，成为我们对神秘未来的独特认识。美娱期望，通过我们的努力，将今日看来电影虚构的故事变为可控的现实。 的本地化字符串。
        /// </summary>
        internal static string Sec_Brand_Mission_Content {
            get {
                return ResourceManager.GetString("Sec_Brand_Mission_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 使命和愿景 的本地化字符串。
        /// </summary>
        internal static string Sec_Brand_Mission_Name {
            get {
                return ResourceManager.GetString("Sec_Brand_Mission_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 杯咖啡 的本地化字符串。
        /// </summary>
        internal static string Sec_Coffee_01 {
            get {
                return ResourceManager.GetString("Sec_Coffee_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 个创意 的本地化字符串。
        /// </summary>
        internal static string Sec_Coffee_02 {
            get {
                return ResourceManager.GetString("Sec_Coffee_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 年学习和研究 的本地化字符串。
        /// </summary>
        internal static string Sec_Coffee_03 {
            get {
                return ResourceManager.GetString("Sec_Coffee_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 行代码 的本地化字符串。
        /// </summary>
        internal static string Sec_Coffee_04 {
            get {
                return ResourceManager.GetString("Sec_Coffee_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 若不是情怀，还有什么是指向远方的星辰 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关于情怀的那点事 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们只是有点不安分，想做点事情的人。 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Intro {
            get {
                return ResourceManager.GetString("Sec_Team_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 热爱编程技术，直接参与软件项目架构搭建和编程开发，.Net、Unity3D、HTML5、微信和APP开发程序猿；致力于VR Object Stream下一代互动超视频技术概念。 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member01_Intro {
            get {
                return ResourceManager.GetString("Sec_Team_Member01_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 https://www.linkedin.com/in/frank-shen-a527445/ 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member01_LinkedIn {
            get {
                return ResourceManager.GetString("Sec_Team_Member01_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 沈震群 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member01_Name {
            get {
                return ResourceManager.GetString("Sec_Team_Member01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创始人 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member01_Title {
            get {
                return ResourceManager.GetString("Sec_Team_Member01_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 海龟二孩妈，喜欢孩子，为小朋友学习伤透脑筋；自己爱好的是穷游，所有时间都在琢磨旅游经，圈子里的旅游达人。 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member02_Intro {
            get {
                return ResourceManager.GetString("Sec_Team_Member02_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 https://www.linkedin.com/in/%E8%89%B3-%E6%B2%88-45559bb5/ 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member02_LinkedIn {
            get {
                return ResourceManager.GetString("Sec_Team_Member02_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 沈艳 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member02_Name {
            get {
                return ResourceManager.GetString("Sec_Team_Member02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联合创始人 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Member02_Title {
            get {
                return ResourceManager.GetString("Sec_Team_Member02_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 团队成员 的本地化字符串。
        /// </summary>
        internal static string Sec_Team_Title {
            get {
                return ResourceManager.GetString("Sec_Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Dec, 2010 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2010A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2010A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 建立吴江市第一个动作捕捉研究实验室。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2010A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2010A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 May, 2010 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2010B_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2010B_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 苏州美娱网络科技有限公司注册成立。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2010B_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2010B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Oct, 2010 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2010C_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2010C_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 沈震群获得“吴江科技创新创业领军人才”称号和相应支持。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2010C_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2010C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Dec, 2011 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2011A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2011A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “互动演艺”测试原型在实验室通过200人同屏模拟。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2011A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2011A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Oct, 2011 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2011B_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2011B_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 沈震群获得“吴江文化重点人才”称号。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2011B_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2011B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Nov, 2011 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2011C_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2011C_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 丁振加入美娱，担任CTO。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2011C_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2011C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Jun, 2012 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2012A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2012A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “互动卡通”之“呜咪讲故事”初步完成Android版开发。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2012A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2012A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Jun, 2012 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2012B_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2012B_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “大胃街区”iOS版本在苹果在线商店上线。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2012B_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2012B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Sept, 2013 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2013A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2013A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “VR高压变电站仿真培训系统”交付给南网电科院并获得好评。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2013A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2013A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Jan, 2014 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2014A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2014A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “震泽古镇”虚拟旅游交付，支持web嵌入和Android/iOS系统。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2014A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2014A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Oct, 2014 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2014B_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2014B_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参加Intel Realsense应用技术开发合作。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2014B_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2014B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Aug, 2015 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2015A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2015A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “天睿房产”在线撮合成交额超过6亿元人民币。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2015A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2015A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Oct, 2015 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2015B_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2015B_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “互动卡通”项目获得微软Microsoft BizSpark项目支持。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2015B_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2015B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Jun, 2017 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2017A_Date {
            get {
                return ResourceManager.GetString("Sec_Timeline_2017A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目变更为“英语爸爸” - 整合式英语启蒙和学习服务 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_2017A_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_2017A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 折叠 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_Hide {
            get {
                return ResourceManager.GetString("Sec_Timeline_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创新从不止步，昨日的曲折只是明天更坚实的基础。 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_Intro {
            get {
                return ResourceManager.GetString("Sec_Timeline_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_LoadMore {
            get {
                return ResourceManager.GetString("Sec_Timeline_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发展历程 的本地化字符串。
        /// </summary>
        internal static string Sec_Timeline_Title {
            get {
                return ResourceManager.GetString("Sec_Timeline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Todo_01_Content {
            get {
                return ResourceManager.GetString("Sec_Todo_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 做有意义的事 的本地化字符串。
        /// </summary>
        internal static string Sec_Todo_01_Name {
            get {
                return ResourceManager.GetString("Sec_Todo_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Todo_02_Content {
            get {
                return ResourceManager.GetString("Sec_Todo_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 不甘平凡，勇于探索 的本地化字符串。
        /// </summary>
        internal static string Sec_Todo_02_Name {
            get {
                return ResourceManager.GetString("Sec_Todo_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Todo_03_Content {
            get {
                return ResourceManager.GetString("Sec_Todo_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人性导向 的本地化字符串。
        /// </summary>
        internal static string Sec_Todo_03_Name {
            get {
                return ResourceManager.GetString("Sec_Todo_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady-关于苏州美娱 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
