//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Home_Services {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Home_Services() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Home_Services", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 炫酷样式，以HTML5响应式设计，满足多个终端显示，超级兼容，使用户体验达到极致。 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_01_Content {
            get {
                return ResourceManager.GetString("Sec_Business_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站设计 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_01_Name {
            get {
                return ResourceManager.GetString("Sec_Business_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 专业手机应用开发,提供基于Android,Windows Phone,iOS等平台的手机应用开发。 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_02_Content {
            get {
                return ResourceManager.GetString("Sec_Business_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手机应用 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_02_Name {
            get {
                return ResourceManager.GetString("Sec_Business_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 根据用户需求特征，个性化设计营销方案。 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_03_Content {
            get {
                return ResourceManager.GetString("Sec_Business_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 在线营销 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_03_Name {
            get {
                return ResourceManager.GetString("Sec_Business_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 针对企业业务流程提高个性化软件开发，涵盖ERP、CRM、业务管理、数据分析、营销发布。 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_04_Content {
            get {
                return ResourceManager.GetString("Sec_Business_04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 软件开发 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_04_Name {
            get {
                return ResourceManager.GetString("Sec_Business_04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提供各种与网站优化相关的SEO建议、实施、监测的服务。 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_05_Content {
            get {
                return ResourceManager.GetString("Sec_Business_05_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 搜索优化 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_05_Name {
            get {
                return ResourceManager.GetString("Sec_Business_05_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 将企业信息、服务、活动等内容通过微信网页的方式发布，面向人脉关系进行社会化推广。可与企业核心系统对接。 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_06_Content {
            get {
                return ResourceManager.GetString("Sec_Business_06_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 微信开发 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_06_Name {
            get {
                return ResourceManager.GetString("Sec_Business_06_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 业务范围 的本地化字符串。
        /// </summary>
        internal static string Sec_Business_Title {
            get {
                return ResourceManager.GetString("Sec_Business_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 有时候，伟大的项目可能源自于不起眼的创意，而看来很伟大的创意也可能是不具备可行性的。我们可以从项目创意阶段起即以专家的身份参与到项目的规划中，从技术和项目执行的角度与客户讨论整体软件项目的需求、架构、周期和性能指标，为软件项目的成功奠定坚实的基础。 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_01_Content {
            get {
                return ResourceManager.GetString("Sec_Contents_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 1. 项目创意、咨询服务 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_01_Name {
            get {
                return ResourceManager.GetString("Sec_Contents_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 许多客户并不精通将自己的需求描述为可见的文字和图表。但是，这对于软件项目来说，常常是必不可少的。文档不仅仅用于我们与客户之间商定项目的需求和目标，也是我们在后续执行过程中日常控制的依据。对于擅长项目文档的客户，这很好，我们能够精确地知道我们该做什么，该怎么做；对于没有项目文档的客户，没关系，我们可以和您一起，把项目的方方面面描述为软件项目的语言。 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_02_Content {
            get {
                return ResourceManager.GetString("Sec_Contents_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 2. 项目控制和管理 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_02_Name {
            get {
                return ResourceManager.GetString("Sec_Contents_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们欢迎客户提供完整的美术资源，但是对于需要我们来完成这个环节的客户，我们可以提供从创意、设定到最终图片或三维模型制作的全过程。也可以与您一起寻找和评估合适的专业美术外包团队。我们也能够采用客户提供的模型，配合我们的动作捕捉设备，来生成栩栩如生的动画资源。 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_03_Content {
            get {
                return ResourceManager.GetString("Sec_Contents_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 3. 开发和设计 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_03_Name {
            get {
                return ResourceManager.GetString("Sec_Contents_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_Introduction {
            get {
                return ResourceManager.GetString("Sec_Contents_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 站在客户角度思考项目，我们不是简单的代码加工者。 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_Slogan {
            get {
                return ResourceManager.GetString("Sec_Contents_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们努力让您的工作变得简单 的本地化字符串。
        /// </summary>
        internal static string Sec_Contents_Title {
            get {
                return ResourceManager.GetString("Sec_Contents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 若不是情怀，还有什么是指向远方的星辰 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 专注于一种技术 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 纷繁复杂，仅取其一 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 多年来围绕微软.Net编程技术体系所积累的知识、经验、合作伙伴关系，都将助力于您的需求实现。 的本地化字符串。
        /// </summary>
        internal static string Sec_Technologies_Introduction {
            get {
                return ResourceManager.GetString("Sec_Technologies_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编程世界很大 的本地化字符串。
        /// </summary>
        internal static string Sec_Technologies_Slogan {
            get {
                return ResourceManager.GetString("Sec_Technologies_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 因此，我们只专注于一类开发技术 的本地化字符串。
        /// </summary>
        internal static string Sec_Technologies_Title {
            get {
                return ResourceManager.GetString("Sec_Technologies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady-产品与服务 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
