//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Yingyu88_Evolution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Yingyu88_Evolution() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Yingyu88_Evolution", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 美娱最初由“互动演艺平台”的产品构想和对于虚拟现实、体感控制、人机智能等前沿技术的热情，开始了技术探索、试验和产品开发。但是由于产品设计合理性、自身技术实力、产业上下游技术成熟度、硬件普及程度、市场热点变迁等因素影响，项目变更为“互动卡通”，再调整为“英语爸爸”项目。 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成功与否，不能左右持续改进的脚步和对革新的思索 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”项目变迁历程 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_imadyCartoon_Content {
            get {
                return ResourceManager.GetString("Sec_imadyCartoon_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 (2012) 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyCartoon_Date {
            get {
                return ResourceManager.GetString("Sec_imadyCartoon_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第二阶段 - “imady互动卡通” 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyCartoon_Name {
            get {
                return ResourceManager.GetString("Sec_imadyCartoon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “imady互动卡通”是基于“imady互动演艺平台”技术基础之上面向幼早教市场开发的创新应用服务。早教教师通过动作捕捉技术，远程扮演卡通形象，并以这种小朋友最喜爱的形式，在客厅大屏幕上传递早教信息，做到真正的“寓教于乐”！ 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyCartoon_Para1 {
            get {
                return ResourceManager.GetString("Sec_imadyCartoon_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_imadyCartoon_Para2 {
            get {
                return ResourceManager.GetString("Sec_imadyCartoon_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_imadyPlatform_Content {
            get {
                return ResourceManager.GetString("Sec_imadyPlatform_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 (2011) 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyPlatform_Date {
            get {
                return ResourceManager.GetString("Sec_imadyPlatform_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第一阶段 - “imady互动演艺” 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyPlatform_Name {
            get {
                return ResourceManager.GetString("Sec_imadyPlatform_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “imady互动演唱会”是基于imady互动演艺平台开发、面向互联网实时虚拟互动娱乐应用的大型网络系统。在技术层面，涉及到实时动捕、全身体感、动作识别、三维图形实时渲染、大并发高流量数据传输和交换、实时虚拟音效合成、多平台客户端协同等先进而复杂的技术。 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyPlatform_Para1 {
            get {
                return ResourceManager.GetString("Sec_imadyPlatform_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未来，通过智能机顶盒（如Android系统）或者智能电视(如GoogleTV）等设备，并配以Kinect类型的体感操控设备，每个观众都可以经高速互联网接入到我们的虚拟演艺服务器，实时参加线上演出，这就是我们所倡导的未来互动电视理念：每个观众都是节目的一部分。 的本地化字符串。
        /// </summary>
        internal static string Sec_imadyPlatform_Para2 {
            get {
                return ResourceManager.GetString("Sec_imadyPlatform_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Wumi_Content {
            get {
                return ResourceManager.GetString("Sec_Wumi_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 (2013) 的本地化字符串。
        /// </summary>
        internal static string Sec_Wumi_Date {
            get {
                return ResourceManager.GetString("Sec_Wumi_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第三阶段 - “呜咪讲故事” 的本地化字符串。
        /// </summary>
        internal static string Sec_Wumi_Name {
            get {
                return ResourceManager.GetString("Sec_Wumi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “呜咪讲故事”是基于“imady互动卡通”技术基础之上进一步简化产品功能、仅保留核心动捕数据传输和终端渲染的一个过渡性产品，其目标是通过这个版本的产品宣传互动卡通和实时Avatar的概念，从而获取市场关注，并逐步丰富产品的功能，形成可持续发展的产品体系。 的本地化字符串。
        /// </summary>
        internal static string Sec_Wumi_Para1 {
            get {
                return ResourceManager.GetString("Sec_Wumi_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “呜咪讲故事”是最接近于商业化的一个应用产品。但是受限于开发资金等方面的因素，对于产品无法做到持续改进，加上商业化收入模式尚未清晰，美娱决定暂不上线此产品，转而寻求更加完美的产品设计、开发品质和运营模式， 的本地化字符串。
        /// </summary>
        internal static string Sec_Wumi_Para2 {
            get {
                return ResourceManager.GetString("Sec_Wumi_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_Content {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 (2017) 的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_Date {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 今天 - “英语爸爸” 的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_Name {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”从前几个以技术导向的产品阶段走出来，反思了我们所遗漏和忽视的，却至为重要的因素 - 人文。结合创始人自己在培育孩子方面的经历，我们意识到，先进而优秀的智能产品虽能起到良好的辅助，却并非陪伴孩子的唯一方式。
        ///技术固然重要，但如果过于追求完美，过度停留在技术研发上，对于产品和业务来说将是一场灾难。 的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_Para1 {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”在过去的项目基础上全新起航。与以往不同的是，“英语爸爸”并非某种软件或技术，而首先是一种宣扬父母关怀的理念。“英语爸爸”将以理念宣扬和教育服务提供为基础，以逐步发展和完善功能的智能产品为辅助工具，最终实现把学习快乐带回给孩子们的想法。 的本地化字符串。
        /// </summary>
        internal static string Sec_Yingyu88_Para2 {
            get {
                return ResourceManager.GetString("Sec_Yingyu88_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Yingyu88 - 项目变迁历程 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
