//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Home_Portfolio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Home_Portfolio() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Home_Portfolio", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 学习与探索 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 穿过幽暗的岁月，回首是一串足迹 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 苏州美娱为天睿企业开发的一套整合营销管理工具系统，并与微信公众号运营相衔接，支持全民经纪人业务系统在微信端的运营。项目采用多层架构、分布式部署，后端能够支持桌面软件和微信web页面的多端架构。整体软件基本为自有开发代码，具有一定的伸缩弹性，模块结构清晰，易于扩容和维护。上线以来已经实现在线业务撮合超过7亿元。 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_01_Content {
            get {
                return ResourceManager.GetString("Sec_Project_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Aug 1, 2015 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_01_Date {
            get {
                return ResourceManager.GetString("Sec_Project_01_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 天睿房产 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_01_Name {
            get {
                return ResourceManager.GetString("Sec_Project_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 苏州美娱为震泽古镇开发的三维虚拟游，结合了三维实景建模和720体感全景技术, 将世界各地的旅游者带入这座具有1200年历史的江南古镇。作为震泽古镇申报国家4A景区项目的一部分，实现古镇主要景点的三维仿真呈现和实景全景照片的三维浏览，使得用户可以远程体验古镇的实景和仿真风景。 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_02_Content {
            get {
                return ResourceManager.GetString("Sec_Project_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 特别是在手机App上创新地实现了体感全景这一有趣的体验模式（仿VR眼镜方式）。项目为跨平台开发，实现PC端、Web端和Android/iPhone手机端的兼容性。 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_02_Content1 {
            get {
                return ResourceManager.GetString("Sec_Project_02_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Feb 10, 2014 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_02_Date {
            get {
                return ResourceManager.GetString("Sec_Project_02_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 虚拟震泽古镇 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_02_Name {
            get {
                return ResourceManager.GetString("Sec_Project_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新上岗的电站操作人员面临极大的危险，对于从未实际操作过的高压设备，仅靠传统的文字和图片无法获得直观的认知，因而极易发生事故，造成人员伤亡或者设备损伤。苏州美娱采用三维VR虚拟现实技术，协助南方电网电科院完成了《高压电力设备仿真培训系统》，在一个逼真的220kV变电站三维仿真环境中模拟了高压设备老化预防性试验的全过程，有效提升了电力操作人员学习效率，降低了真实环境中事故的概率。 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_03_Content {
            get {
                return ResourceManager.GetString("Sec_Project_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Feb 20, 2014 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_03_Date {
            get {
                return ResourceManager.GetString("Sec_Project_03_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电科院虚拟高压变电站仿真培训系统 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_03_Name {
            get {
                return ResourceManager.GetString("Sec_Project_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 大胃街区是苏州美娱完全自有知识产权和自主开发的一款轻度社交游戏，融合了社交建设和塔防等两种截然不同的游戏类型。 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_04_Content {
            get {
                return ResourceManager.GetString("Sec_Project_04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 July 1, 2012 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_04_Date {
            get {
                return ResourceManager.GetString("Sec_Project_04_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 大胃街区 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_04_Name {
            get {
                return ResourceManager.GetString("Sec_Project_04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 区区通是一个以邻里社交、智慧社区为方向的互联网产品，技术上采用高并发、高弹性的云技术架构，致力于为中国数十万小区提供智能的生活和社交服务。由苏州美娱提供前期技术服务。 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_05_Content {
            get {
                return ResourceManager.GetString("Sec_Project_05_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Oct 31, 2016 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_05_Date {
            get {
                return ResourceManager.GetString("Sec_Project_05_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邻里社交 的本地化字符串。
        /// </summary>
        internal static string Sec_Project_05_Name {
            get {
                return ResourceManager.GetString("Sec_Project_05_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady-项目案例 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
