//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Home_Contact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Home_Contact() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Home_Contact", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_address {
            get {
                return ResourceManager.GetString("Sec_Contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上海市嘉定区云谷路599弄TEEC上海中心3楼 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_address_content {
            get {
                return ResourceManager.GetString("Sec_Contact_address_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电子邮件 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_email {
            get {
                return ResourceManager.GetString("Sec_Contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 fs@imady.com 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_email_content {
            get {
                return ResourceManager.GetString("Sec_Contact_email_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_phone {
            get {
                return ResourceManager.GetString("Sec_Contact_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 +86 512 63986886 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_phone_content {
            get {
                return ResourceManager.GetString("Sec_Contact_phone_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您的信息目前将以邮件形式发送给我们。谢谢！ 的本地化字符串。
        /// </summary>
        internal static string Sec_Contact_submitprompt {
            get {
                return ResourceManager.GetString("Sec_Contact_submitprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_Button_Send {
            get {
                return ResourceManager.GetString("Sec_Feedback_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电子邮件 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_email {
            get {
                return ResourceManager.GetString("Sec_Feedback_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您的电子邮件 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_email_Placeholder {
            get {
                return ResourceManager.GetString("Sec_Feedback_email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_FirstName {
            get {
                return ResourceManager.GetString("Sec_Feedback_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您的名字 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_FirstName_Placeholder {
            get {
                return ResourceManager.GetString("Sec_Feedback_FirstName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_LastName {
            get {
                return ResourceManager.GetString("Sec_Feedback_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您的姓 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_LastName_Placeholder {
            get {
                return ResourceManager.GetString("Sec_Feedback_LastName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_Message {
            get {
                return ResourceManager.GetString("Sec_Feedback_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请在此写下您的想法 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_Message_Placeholder {
            get {
                return ResourceManager.GetString("Sec_Feedback_Message_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息主题 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_Subject {
            get {
                return ResourceManager.GetString("Sec_Feedback_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 来自用户的反馈 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_Subject_Placeholder {
            get {
                return ResourceManager.GetString("Sec_Feedback_Subject_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 告诉我们您的想法 的本地化字符串。
        /// </summary>
        internal static string Sec_Feedback_Title {
            get {
                return ResourceManager.GetString("Sec_Feedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 聆听 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 期待您的声音 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady-联络我们 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
