//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_SharedLayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_SharedLayout() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_SharedLayout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 关于美娱 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_About {
            get {
                return ResourceManager.GetString("Menu_Home_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady品牌理念 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_About_Phylosophy {
            get {
                return ResourceManager.GetString("Menu_Home_About_Phylosophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 团队成员 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_About_TeamIntro {
            get {
                return ResourceManager.GetString("Menu_Home_About_TeamIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发展历程 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_About_TimeLine {
            get {
                return ResourceManager.GetString("Menu_Home_About_TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_ChangeLanguage {
            get {
                return ResourceManager.GetString("Menu_Home_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 苏州美娱网络科技有限公司 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_companyname {
            get {
                return ResourceManager.GetString("Menu_Home_companyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系我们 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Contact {
            get {
                return ResourceManager.GetString("Menu_Home_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Index {
            get {
                return ResourceManager.GetString("Menu_Home_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目案例 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Portfolio {
            get {
                return ResourceManager.GetString("Menu_Home_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电科院虚拟高压变电站 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Portfolio_Dian {
            get {
                return ResourceManager.GetString("Menu_Home_Portfolio_Dian", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邻里社交 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Portfolio_Ququton {
            get {
                return ResourceManager.GetString("Menu_Home_Portfolio_Ququton", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 天睿房产 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Portfolio_Tianrui {
            get {
                return ResourceManager.GetString("Menu_Home_Portfolio_Tianrui", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 大胃街区 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Portfolio_ToHE {
            get {
                return ResourceManager.GetString("Menu_Home_Portfolio_ToHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 虚拟震泽古镇 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Portfolio_Zhenze {
            get {
                return ResourceManager.GetString("Menu_Home_Portfolio_Zhenze", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 服务 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Services {
            get {
                return ResourceManager.GetString("Menu_Home_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 产品范围 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Services_Business {
            get {
                return ResourceManager.GetString("Menu_Home_Services_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 业务内容 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Services_Contents {
            get {
                return ResourceManager.GetString("Menu_Home_Services_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 技术 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Services_Technologies {
            get {
                return ResourceManager.GetString("Menu_Home_Services_Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英语爸爸 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88 {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 变迁历程 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88_Evolution {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88_Evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 特色 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88_Features {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”是什么 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88_Introduction {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 理念 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88_Phylosophy {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88_Phylosophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 产品形式 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88_Product {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 技术方案 的本地化字符串。
        /// </summary>
        internal static string Menu_Home_Yingyu88_Technologies {
            get {
                return ResourceManager.GetString("Menu_Home_Yingyu88_Technologies", resourceCulture);
            }
        }
    }
}
