//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx_Home_Yingyu88 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx_Home_Yingyu88() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resx_Home_Yingyu88", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 请第一个通知我 的本地化字符串。
        /// </summary>
        internal static string Sec_Coming_ButtonNotify {
            get {
                return ResourceManager.GetString("Sec_Coming_ButtonNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 即将到来 的本地化字符串。
        /// </summary>
        internal static string Sec_Coming_Title {
            get {
                return ResourceManager.GetString("Sec_Coming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 了解更多 的本地化字符串。
        /// </summary>
        internal static string Sec_Evolution_ButtonMore {
            get {
                return ResourceManager.GetString("Sec_Evolution_ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 美娱最初由“互动演艺平台”的产品构想和对于虚拟现实、体感控制、人机智能等前沿技术的热情，开始了技术探索、试验和产品开发。但是由于产品设计合理性、自身技术实力、产业上下游技术成熟度、硬件普及程度、市场热点变迁等因素影响，项目变更为“互动卡通”，再调整为“英语爸爸”项目。 的本地化字符串。
        /// </summary>
        internal static string Sec_Evolution_Intro {
            get {
                return ResourceManager.GetString("Sec_Evolution_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细 的本地化字符串。
        /// </summary>
        internal static string Sec_Evolution_LinkDetail {
            get {
                return ResourceManager.GetString("Sec_Evolution_LinkDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”项目变迁历程 的本地化字符串。
        /// </summary>
        internal static string Sec_Evolution_Title {
            get {
                return ResourceManager.GetString("Sec_Evolution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 采用VR/AR技术开发交互工具，结合Gamification理念，以孩子们的视角改造传统的语言培训模式，使实地游学效果加倍。 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_01_Content {
            get {
                return ResourceManager.GetString("Sec_Features_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首创“VR游学” 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_01_Name {
            get {
                return ResourceManager.GetString("Sec_Features_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 跟随中国官方教学大纲，在此基础上进行内容拓展，并以有趣、好玩的方式，在提升小朋友的学习兴趣的同时，提高课内学习成绩。 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_02_Content {
            get {
                return ResourceManager.GetString("Sec_Features_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_02_Name {
            get {
                return ResourceManager.GetString("Sec_Features_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 精选热爱孩子、且具有教育资质和经验的外教爸爸老师，丰富小朋友男性一侧的思维方式。 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_03_Content {
            get {
                return ResourceManager.GetString("Sec_Features_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 爸爸老师 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_03_Name {
            get {
                return ResourceManager.GetString("Sec_Features_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 按钮、菜单是软件技术发展早期阶段有限互动形式所产生的过渡性设计。随着技术的发展，交互形式最终将回归到以人类行为为核心的阶段。因此，我们的App将尽量采用自然语言、肢体语言交互的形式，最大程度聚焦在核心内容上。 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_04_Content {
            get {
                return ResourceManager.GetString("Sec_Features_04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “无按钮化”界面设计 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_04_Name {
            get {
                return ResourceManager.GetString("Sec_Features_04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首选具有优美地理环境和西方典型人文环境的新西兰作为游学第一站，在美丽而纯净的风光中，建立孩子对英语世界的第一印象。 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_05_Content {
            get {
                return ResourceManager.GetString("Sec_Features_05_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 游学目的地 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_05_Name {
            get {
                return ResourceManager.GetString("Sec_Features_05_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”源自于技术导向的智能项目，却逐渐发现人性内涵的重要。针对中国亲子教育的现状，结合项目创始人的亲身经历，我们努力将人性和父亲关爱融入到项目中，因此“英语爸爸”项目将充满人性关怀。 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_Intro {
            get {
                return ResourceManager.GetString("Sec_Features_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”的核心特色 的本地化字符串。
        /// </summary>
        internal static string Sec_Features_Title {
            get {
                return ResourceManager.GetString("Sec_Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Intro {
            get {
                return ResourceManager.GetString("Sec_Header_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 爸爸的意义 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Header_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成长路漫漫，怎能没有陪伴和守护 的本地化字符串。
        /// </summary>
        internal static string Sec_Header_Title {
            get {
                return ResourceManager.GetString("Sec_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中国经济高速成长，也导致社会节奏快、压力大，决定了这一代父母在孩子教育方面投入关怀不足。即便父亲或者母亲愿意全职看护，由于自身外语能力的制约，也只能是成为孩子们的补课接送车 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_01_Content {
            get {
                return ResourceManager.GetString("Sec_Issues_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关怀缺失 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_01_Name {
            get {
                return ResourceManager.GetString("Sec_Issues_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 外语学习非常讲究语言环境；然而中国人均教育资源非常有限，校内英语课程时间极度不足，而绝大多数家庭均为母语强势环境。因此，中国学生多为机械式外语学习，很难培养出色的语感 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_02_Content {
            get {
                return ResourceManager.GetString("Sec_Issues_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 语境缺失 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_02_Name {
            get {
                return ResourceManager.GetString("Sec_Issues_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中国学校普遍采取大班制教学，且师资缺乏时常导致班级超员，导致能力相差极大的学生按相同的教学目标在同一进度中学习，极易出现部分学生兴趣丧失、而另一部分学生自信丧失的负面现象 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_03_Content {
            get {
                return ResourceManager.GetString("Sec_Issues_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 个性缺失 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_03_Name {
            get {
                return ResourceManager.GetString("Sec_Issues_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 强化记忆导致表象思维强而认知不足。当前英语教学以中文思维主导，偏向词、句、语法的强化学习，却忽视了实际运用能力。中国孩子12年英语学下来，听说写等实际应用能力极其有限，更不要说对英语文化的深入了解和英语逻辑思维的形成。 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_04_Content {
            get {
                return ResourceManager.GetString("Sec_Issues_04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 思维缺失 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_04_Name {
            get {
                return ResourceManager.GetString("Sec_Issues_04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英语学习App数以千计，个个都是填坑选择加判断，顶多就是来个课本电子化或者跟读加自动KTV打分，能给我来个好玩又有想象力的么？ 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_05_Content {
            get {
                return ResourceManager.GetString("Sec_Issues_05_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 教学技术局限 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_05_Name {
            get {
                return ResourceManager.GetString("Sec_Issues_05_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 学完12年英语，都没出过国，没跟老外对过话，没有外国小朋友，这种不合理性还需要解释么？ 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_06_Content {
            get {
                return ResourceManager.GetString("Sec_Issues_06_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 实践缺乏 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_06_Name {
            get {
                return ResourceManager.GetString("Sec_Issues_06_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_Intro {
            get {
                return ResourceManager.GetString("Sec_Issues_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_Slogan {
            get {
                return ResourceManager.GetString("Sec_Issues_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中国式英语教学面对的问题 的本地化字符串。
        /// </summary>
        internal static string Sec_Issues_Title {
            get {
                return ResourceManager.GetString("Sec_Issues_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提倡父母尤其是爸爸深度参与孩子的英语学习，陪伴多于监督，在融洽的氛围中消除对外语学习的恐惧。 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_01_Content {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 爸爸的陪伴 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_01_Name {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 正视动漫、游戏充斥的世界，如果英语学习不能更加快乐，我们怎么才能吸引孩子们的视线？ 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_02_Content {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 快乐好玩 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_02_Name {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们反对机械、无创意的软件设计，倡导&quot;去按钮化“的自然互动方式，使智慧技术真正变成有人性的辅助工具。 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_03_Content {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 智慧技术辅助 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_03_Name {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 游学不止于旅游，学习更需要实践。结合在线虚拟语境的反复训练和实地游学的亲身感受，强化最终学习效果。 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_04_Content {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 VR在线 + 实地游学 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_04_Name {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 固定式外教，针对每个孩子的特点因人施教，跟随孩子的节奏，耐心和等待，呵护成长。 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_05_Content {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_05_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人性化教学 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_05_Name {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_05_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我们不生产鹦鹉！磨耳朵、磨舌头，必须还要打造一个有思想、能表达、善于沟通的人。 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_06_Content {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_06_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 语言学习 + 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_06_Name {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_06_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”努力探索英语早期学习的最优实践，希望通过我们的产品和服务，能够把父母关爱、学习的愉悦和成就的欣喜统一起来，改变当前大家对英语学习枯燥、单一的认识。 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_Intro {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 爱孩子，陪孩子，你就是“英语爸爸”！ 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_PreTitle {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_PreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”的理念 的本地化字符串。
        /// </summary>
        internal static string Sec_Phylosophy_Title {
            get {
                return ResourceManager.GetString("Sec_Phylosophy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基于VR、AI等技术理念，针对外语教育特点而专门设计开发的游戏化教学平台。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component01_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Component01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 智能化App 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component01_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Component01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 精心挑选西方国家具有资质和教学经验的老师，遵循中国官方大纲，固定式教学。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component02_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Component02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 线上外教 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component02_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Component02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关心孩子学习和成长的爸爸们交流英语学习指导心得和经验的线上社区。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component03_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Component03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 爸爸日志 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component03_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Component03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 帮助中国小朋友与外国小朋友建立一对一互帮互助，促进中外学生文化交流。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component04_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Component04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创新中外互动社区 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component04_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Component04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component_Intro {
            get {
                return ResourceManager.GetString("Sec_Product_Component_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component_Slogan {
            get {
                return ResourceManager.GetString("Sec_Product_Component_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”的产品形式 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Component_Title {
            get {
                return ResourceManager.GetString("Sec_Product_Component_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”是专注于K12英语快乐学习的垂直整合式服务，致力于将家庭关怀、智慧互动教学、游学实践、快乐学习带回到孩子们的英语学习过程中，帮助孩子们在提升校内英语成绩的同时，获得愉快的体验、实际运用语言的能力、美好的学习记忆。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Intro {
            get {
                return ResourceManager.GetString("Sec_Product_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”是什么 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 通过同步强化、虚拟语境建立、弱点补足等服务，帮助小朋友（尤其是一、二年级阶段）提升校内英语成绩、建立自信。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service01_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Service01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 校内课程强化 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service01_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Service01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 紧密围绕官方英语大纲和教学节奏的前提下，针对每个阶段的重要学点，推荐相应主题的拓展听力、阅读、对话游戏，强化核心知识。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service02_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Service02_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 延伸拓展 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service02_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Service02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基于智能化互动技术，在好玩有趣、充满美感的虚拟语境中，以接近英语原生学习的方式，帮助小朋友在不知不觉中建立英语语感。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service03_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Service03_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 在线游学 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service03_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Service03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 亲子组团境外游学，参加当地名校短期国际课程，并实地体验当地风土人情和日常生活，零距离与社区互动，强效实践外语应用。 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service04_Content {
            get {
                return ResourceManager.GetString("Sec_Product_Service04_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 实地游学 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Service04_Name {
            get {
                return ResourceManager.GetString("Sec_Product_Service04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 “英语爸爸”是快乐学习英语的一站式整合服务 的本地化字符串。
        /// </summary>
        internal static string Sec_Product_Slogan {
            get {
                return ResourceManager.GetString("Sec_Product_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 imady-英语爸爸 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
